# Generated by Django 3.1.7 on 2021-03-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routecard',
            name='day',
        ),
        migrations.AddField(
            model_name='busoperator',
            name='total_seats',
            field=models.IntegerField(default=525),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routecard',
            name='total_seats',
            field=models.IntegerField(default=52),
        ),
    ]
